// flow-typed signature: 282fe692a1c221347c3f702f9ba3218f
// flow-typed version: <<STUB>>/eslint-config-synacor_v^2.0.2/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-synacor'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-synacor' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config-synacor/src/index' {
  declare module.exports: any;
}

declare module 'eslint-config-synacor/src/rules/compatibility' {
  declare module.exports: any;
}

declare module 'eslint-config-synacor/src/rules/react' {
  declare module.exports: any;
}

declare module 'eslint-config-synacor/src/rules/security' {
  declare module.exports: any;
}

declare module 'eslint-config-synacor/src/rules/style' {
  declare module.exports: any;
}

declare module 'eslint-config-synacor/src/rules/tests' {
  declare module.exports: any;
}

declare module 'eslint-config-synacor/src/test-rules' {
  declare module.exports: any;
}

declare module 'eslint-config-synacor/test-rules' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-config-synacor/index' {
  declare module.exports: $Exports<'eslint-config-synacor'>;
}
declare module 'eslint-config-synacor/index.js' {
  declare module.exports: $Exports<'eslint-config-synacor'>;
}
declare module 'eslint-config-synacor/src/index.js' {
  declare module.exports: $Exports<'eslint-config-synacor/src/index'>;
}
declare module 'eslint-config-synacor/src/rules/compatibility.js' {
  declare module.exports: $Exports<'eslint-config-synacor/src/rules/compatibility'>;
}
declare module 'eslint-config-synacor/src/rules/react.js' {
  declare module.exports: $Exports<'eslint-config-synacor/src/rules/react'>;
}
declare module 'eslint-config-synacor/src/rules/security.js' {
  declare module.exports: $Exports<'eslint-config-synacor/src/rules/security'>;
}
declare module 'eslint-config-synacor/src/rules/style.js' {
  declare module.exports: $Exports<'eslint-config-synacor/src/rules/style'>;
}
declare module 'eslint-config-synacor/src/rules/tests.js' {
  declare module.exports: $Exports<'eslint-config-synacor/src/rules/tests'>;
}
declare module 'eslint-config-synacor/src/test-rules.js' {
  declare module.exports: $Exports<'eslint-config-synacor/src/test-rules'>;
}
declare module 'eslint-config-synacor/test-rules.js' {
  declare module.exports: $Exports<'eslint-config-synacor/test-rules'>;
}
