// flow-typed signature: 0a3def96b8fa7239deb7b0e9d113511a
// flow-typed version: <<STUB>>/mobx-preact_v1.1.0/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mobx-preact'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mobx-preact' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mobx-preact/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'mobx-preact/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'mobx-preact/dist/bundle' {
  declare module.exports: any;
}

declare module 'mobx-preact/lib/connect' {
  declare module.exports: any;
}

declare module 'mobx-preact/lib/index' {
  declare module.exports: any;
}

declare module 'mobx-preact/lib/inject' {
  declare module.exports: any;
}

declare module 'mobx-preact/lib/observer' {
  declare module.exports: any;
}

declare module 'mobx-preact/lib/Provider' {
  declare module.exports: any;
}

declare module 'mobx-preact/lib/utils/utils' {
  declare module.exports: any;
}

declare module 'mobx-preact/sample/dist/sample.bundle' {
  declare module.exports: any;
}

declare module 'mobx-preact/sample/dist/sample.es5' {
  declare module.exports: any;
}

declare module 'mobx-preact/sample/rollup.config' {
  declare module.exports: any;
}

declare module 'mobx-preact/sample/sample' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mobx-preact/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'mobx-preact/coverage/lcov-report/prettify'>;
}
declare module 'mobx-preact/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'mobx-preact/coverage/lcov-report/sorter'>;
}
declare module 'mobx-preact/dist/bundle.js' {
  declare module.exports: $Exports<'mobx-preact/dist/bundle'>;
}
declare module 'mobx-preact/lib/connect.js' {
  declare module.exports: $Exports<'mobx-preact/lib/connect'>;
}
declare module 'mobx-preact/lib/index.js' {
  declare module.exports: $Exports<'mobx-preact/lib/index'>;
}
declare module 'mobx-preact/lib/inject.js' {
  declare module.exports: $Exports<'mobx-preact/lib/inject'>;
}
declare module 'mobx-preact/lib/observer.js' {
  declare module.exports: $Exports<'mobx-preact/lib/observer'>;
}
declare module 'mobx-preact/lib/Provider.js' {
  declare module.exports: $Exports<'mobx-preact/lib/Provider'>;
}
declare module 'mobx-preact/lib/utils/utils.js' {
  declare module.exports: $Exports<'mobx-preact/lib/utils/utils'>;
}
declare module 'mobx-preact/sample/dist/sample.bundle.js' {
  declare module.exports: $Exports<'mobx-preact/sample/dist/sample.bundle'>;
}
declare module 'mobx-preact/sample/dist/sample.es5.js' {
  declare module.exports: $Exports<'mobx-preact/sample/dist/sample.es5'>;
}
declare module 'mobx-preact/sample/rollup.config.js' {
  declare module.exports: $Exports<'mobx-preact/sample/rollup.config'>;
}
declare module 'mobx-preact/sample/sample.js' {
  declare module.exports: $Exports<'mobx-preact/sample/sample'>;
}
