// flow-typed signature: 6e17baa4552bc91d4d7fd61ee757c68a
// flow-typed version: <<STUB>>/preact-mobx_v^0.1.4/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'preact-mobx'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'preact-mobx' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'preact-mobx/dist/index' {
  declare module.exports: any;
}

declare module 'preact-mobx/dist/observer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'preact-mobx/dist/index.js' {
  declare module.exports: $Exports<'preact-mobx/dist/index'>;
}
declare module 'preact-mobx/dist/observer.js' {
  declare module.exports: $Exports<'preact-mobx/dist/observer'>;
}
