// flow-typed signature: 384e5766e7dd260437fefb5fa04c6d3e
// flow-typed version: <<STUB>>/preact_v8.2.7/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'preact'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'preact' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'preact/debug' {
  declare module.exports: any;
}

declare module 'preact/debug/index' {
  declare module.exports: any;
}

declare module 'preact/devtools' {
  declare module.exports: any;
}

declare module 'preact/devtools/devtools' {
  declare module.exports: any;
}

declare module 'preact/devtools/index' {
  declare module.exports: any;
}

declare module 'preact/dist/preact.dev' {
  declare module.exports: any;
}

declare module 'preact/dist/preact.esm' {
  declare module.exports: any;
}

declare module 'preact/dist/preact' {
  declare module.exports: any;
}

declare module 'preact/dist/preact.min' {
  declare module.exports: any;
}

declare module 'preact/src/clone-element' {
  declare module.exports: any;
}

declare module 'preact/src/component' {
  declare module.exports: any;
}

declare module 'preact/src/constants' {
  declare module.exports: any;
}

declare module 'preact/src/dom/index' {
  declare module.exports: any;
}

declare module 'preact/src/h' {
  declare module.exports: any;
}

declare module 'preact/src/options' {
  declare module.exports: any;
}

declare module 'preact/src/preact' {
  declare module.exports: any;
}

declare module 'preact/src/render-queue' {
  declare module.exports: any;
}

declare module 'preact/src/render' {
  declare module.exports: any;
}

declare module 'preact/src/util' {
  declare module.exports: any;
}

declare module 'preact/src/vdom/component-recycler' {
  declare module.exports: any;
}

declare module 'preact/src/vdom/component' {
  declare module.exports: any;
}

declare module 'preact/src/vdom/diff' {
  declare module.exports: any;
}

declare module 'preact/src/vdom/index' {
  declare module.exports: any;
}

declare module 'preact/src/vnode' {
  declare module.exports: any;
}

// Filename aliases
declare module 'preact/debug.js' {
  declare module.exports: $Exports<'preact/debug'>;
}
declare module 'preact/debug/index.js' {
  declare module.exports: $Exports<'preact/debug/index'>;
}
declare module 'preact/devtools.js' {
  declare module.exports: $Exports<'preact/devtools'>;
}
declare module 'preact/devtools/devtools.js' {
  declare module.exports: $Exports<'preact/devtools/devtools'>;
}
declare module 'preact/devtools/index.js' {
  declare module.exports: $Exports<'preact/devtools/index'>;
}
declare module 'preact/dist/preact.dev.js' {
  declare module.exports: $Exports<'preact/dist/preact.dev'>;
}
declare module 'preact/dist/preact.esm.js' {
  declare module.exports: $Exports<'preact/dist/preact.esm'>;
}
declare module 'preact/dist/preact.js' {
  declare module.exports: $Exports<'preact/dist/preact'>;
}
declare module 'preact/dist/preact.min.js' {
  declare module.exports: $Exports<'preact/dist/preact.min'>;
}
declare module 'preact/src/clone-element.js' {
  declare module.exports: $Exports<'preact/src/clone-element'>;
}
declare module 'preact/src/component.js' {
  declare module.exports: $Exports<'preact/src/component'>;
}
declare module 'preact/src/constants.js' {
  declare module.exports: $Exports<'preact/src/constants'>;
}
declare module 'preact/src/dom/index.js' {
  declare module.exports: $Exports<'preact/src/dom/index'>;
}
declare module 'preact/src/h.js' {
  declare module.exports: $Exports<'preact/src/h'>;
}
declare module 'preact/src/options.js' {
  declare module.exports: $Exports<'preact/src/options'>;
}
declare module 'preact/src/preact.js' {
  declare module.exports: $Exports<'preact/src/preact'>;
}
declare module 'preact/src/render-queue.js' {
  declare module.exports: $Exports<'preact/src/render-queue'>;
}
declare module 'preact/src/render.js' {
  declare module.exports: $Exports<'preact/src/render'>;
}
declare module 'preact/src/util.js' {
  declare module.exports: $Exports<'preact/src/util'>;
}
declare module 'preact/src/vdom/component-recycler.js' {
  declare module.exports: $Exports<'preact/src/vdom/component-recycler'>;
}
declare module 'preact/src/vdom/component.js' {
  declare module.exports: $Exports<'preact/src/vdom/component'>;
}
declare module 'preact/src/vdom/diff.js' {
  declare module.exports: $Exports<'preact/src/vdom/diff'>;
}
declare module 'preact/src/vdom/index.js' {
  declare module.exports: $Exports<'preact/src/vdom/index'>;
}
declare module 'preact/src/vnode.js' {
  declare module.exports: $Exports<'preact/src/vnode'>;
}
