// flow-typed signature: 336a89b3d23313399e48748e3af3bcbc
// flow-typed version: <<STUB>>/preact-render-spy_v^1.2.1/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'preact-render-spy'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'preact-render-spy' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'preact-render-spy/snapshot' {
  declare module.exports: any;
}

declare module 'preact-render-spy/src/is-where' {
  declare module.exports: any;
}

declare module 'preact-render-spy/src/preact-render-spy' {
  declare module.exports: any;
}

declare module 'preact-render-spy/src/sel-to-where' {
  declare module.exports: any;
}

declare module 'preact-render-spy/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'preact-render-spy/index' {
  declare module.exports: $Exports<'preact-render-spy'>;
}
declare module 'preact-render-spy/index.js' {
  declare module.exports: $Exports<'preact-render-spy'>;
}
declare module 'preact-render-spy/snapshot.js' {
  declare module.exports: $Exports<'preact-render-spy/snapshot'>;
}
declare module 'preact-render-spy/src/is-where.js' {
  declare module.exports: $Exports<'preact-render-spy/src/is-where'>;
}
declare module 'preact-render-spy/src/preact-render-spy.js' {
  declare module.exports: $Exports<'preact-render-spy/src/preact-render-spy'>;
}
declare module 'preact-render-spy/src/sel-to-where.js' {
  declare module.exports: $Exports<'preact-render-spy/src/sel-to-where'>;
}
declare module 'preact-render-spy/webpack.config.js' {
  declare module.exports: $Exports<'preact-render-spy/webpack.config'>;
}
